export const Strings = {
  ar: {
    appName: 'محول Base64 PDF',
    home: 'الرئيسية',
    base64ToPdf: 'Base64 إلى PDF',
    pdfToBase64: 'PDF إلى Base64',
    history: 'السجل',
    settings: 'الإعدادات',
    convert: 'تحويل',
    converting: 'جاري التحويل...',
    paste: 'لصق',
    copy: 'نسخ',
    clear: 'مسح',
    save: 'حفظ',
    share: 'مشاركة',
    selectFile: 'اختر ملف',
    selectPdf: 'اختر ملف PDF',
    enterBase64: 'أدخل نص Base64 هنا...',
    base64Output: 'نتيجة Base64',
    conversionSuccess: 'تم التحويل بنجاح!',
    conversionError: 'حدث خطأ في التحويل',
    invalidBase64: 'نص Base64 غير صالح',
    noFileSelected: 'لم يتم اختيار ملف',
    fileSaved: 'تم حفظ الملف',
    copiedToClipboard: 'تم النسخ إلى الحافظة',
    darkMode: 'الوضع الداكن',
    language: 'اللغة',
    clearHistory: 'مسح السجل',
    about: 'حول التطبيق',
    version: 'الإصدار',
    rateApp: 'قيم التطبيق',
    privacyPolicy: 'سياسة الخصوصية',
    noHistory: 'لا يوجد سجل',
    deleteAll: 'حذف الكل',
    fileName: 'اسم الملف',
    fileSize: 'حجم الملف',
    date: 'التاريخ',
    type: 'النوع',
    welcomeTitle: 'مرحباً بك في محول Base64 PDF',
    welcomeSubtitle: 'حول ملفات PDF إلى Base64 والعكس بسهولة',
    feature1Title: 'تحويل سريع',
    feature1Desc: 'تحويل فوري بين Base64 و PDF',
    feature2Title: 'حفظ ومشاركة',
    feature2Desc: 'احفظ الملفات وشاركها بسهولة',
    feature3Title: 'سجل التحويلات',
    feature3Desc: 'تتبع جميع تحويلاتك السابقة',
    startConverting: 'ابدأ التحويل',
  },
  en: {
    appName: 'Base64 PDF Converter',
    home: 'Home',
    base64ToPdf: 'Base64 to PDF',
    pdfToBase64: 'PDF to Base64',
    history: 'History',
    settings: 'Settings',
    convert: 'Convert',
    converting: 'Converting...',
    paste: 'Paste',
    copy: 'Copy',
    clear: 'Clear',
    save: 'Save',
    share: 'Share',
    selectFile: 'Select File',
    selectPdf: 'Select PDF File',
    enterBase64: 'Enter Base64 text here...',
    base64Output: 'Base64 Output',
    conversionSuccess: 'Conversion successful!',
    conversionError: 'Conversion error',
    invalidBase64: 'Invalid Base64 text',
    noFileSelected: 'No file selected',
    fileSaved: 'File saved',
    copiedToClipboard: 'Copied to clipboard',
    darkMode: 'Dark Mode',
    language: 'Language',
    clearHistory: 'Clear History',
    about: 'About',
    version: 'Version',
    rateApp: 'Rate App',
    privacyPolicy: 'Privacy Policy',
    noHistory: 'No history',
    deleteAll: 'Delete All',
    fileName: 'File Name',
    fileSize: 'File Size',
    date: 'Date',
    type: 'Type',
    welcomeTitle: 'Welcome to Base64 PDF Converter',
    welcomeSubtitle: 'Convert PDF files to Base64 and vice versa easily',
    feature1Title: 'Fast Conversion',
    feature1Desc: 'Instant conversion between Base64 and PDF',
    feature2Title: 'Save & Share',
    feature2Desc: 'Save files and share them easily',
    feature3Title: 'Conversion History',
    feature3Desc: 'Track all your previous conversions',
    startConverting: 'Start Converting',
  },
};
